export * from './Heading'
export { default as Heading } from './Heading'
export * from './Paragraph'
export { default as Paragraph } from './Paragraph'
export * from './Text'
export { default as Text } from './Text'
export * from './Verse'
export { default as Verse } from './Verse'
