export { default as HomepageAboutMe } from './HomepageAboutMe'
export { default as HomepageCTA } from './HomepageCTA'
export { default as HomepageHero } from './HomepageHero'
export { default as HomepageProject } from './HomepageProject'
export { default as HomepageServices } from './HomepageServices'
